//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PawnPlus.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PawnPlus.Core.Localizations.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be empty..
        /// </summary>
        public static string Error_EmptyName {
            get {
                return ResourceManager.GetString("Error_EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path cannot be empty..
        /// </summary>
        public static string Error_PathEmpty {
            get {
                return ResourceManager.GetString("Error_PathEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot;{0}&quot; was not found..
        /// </summary>
        public static string Exception_FileNotFound {
            get {
                return ResourceManager.GetString("Exception_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is an invalid plugin..
        /// </summary>
        public static string Exception_InvalidPlugin {
            get {
                return ResourceManager.GetString("Exception_InvalidPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t load project because the file &quot;{0}&quot; was not found..
        /// </summary>
        public static string Exception_ProjectFileNotFound {
            get {
                return ResourceManager.GetString("Exception_ProjectFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find and Replace.
        /// </summary>
        public static string Name_FindReplace {
            get {
                return ResourceManager.GetString("Name_FindReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Line.
        /// </summary>
        public static string Name_GoToLine {
            get {
                return ResourceManager.GetString("Name_GoToLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Name_Output {
            get {
                return ResourceManager.GetString("Name_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Explorer.
        /// </summary>
        public static string Name_ProjectExplorer {
            get {
                return ResourceManager.GetString("Name_ProjectExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column {0}.
        /// </summary>
        public static string Status_Column {
            get {
                return ResourceManager.GetString("Status_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiled.
        /// </summary>
        public static string Status_Compiled {
            get {
                return ResourceManager.GetString("Status_Compiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiled with errors.
        /// </summary>
        public static string Status_CompiledError {
            get {
                return ResourceManager.GetString("Status_CompiledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiling....
        /// </summary>
        public static string Status_Compiling {
            get {
                return ResourceManager.GetString("Status_Compiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current document is empty.
        /// </summary>
        public static string Status_EmptyText {
            get {
                return ResourceManager.GetString("Status_EmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying include files....
        /// </summary>
        public static string Status_IncludesCopying {
            get {
                return ResourceManager.GetString("Status_IncludesCopying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting include files....
        /// </summary>
        public static string Status_IncludesDeleting {
            get {
                return ResourceManager.GetString("Status_IncludesDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line {0}.
        /// </summary>
        public static string Status_Line {
            get {
                return ResourceManager.GetString("Status_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Status_Ready {
            get {
                return ResourceManager.GetString("Status_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving files....
        /// </summary>
        public static string Status_SavingFiles {
            get {
                return ResourceManager.GetString("Status_SavingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.{1}.{2}.
        /// </summary>
        public static string Status_Version {
            get {
                return ResourceManager.GetString("Status_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Text_Add {
            get {
                return ResourceManager.GetString("Text_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Documents.
        /// </summary>
        public static string Text_AllDocuments {
            get {
                return ResourceManager.GetString("Text_AllDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Text_Browse {
            get {
                return ResourceManager.GetString("Text_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        public static string Text_Build {
            get {
                return ResourceManager.GetString("Text_Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Text_Cancel {
            get {
                return ResourceManager.GetString("Text_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Sensitive.
        /// </summary>
        public static string Text_CaseSensitive {
            get {
                return ResourceManager.GetString("Text_CaseSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking files....
        /// </summary>
        public static string Text_CheckingFiles {
            get {
                return ResourceManager.GetString("Text_CheckingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Text_Close {
            get {
                return ResourceManager.GetString("Text_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Project.
        /// </summary>
        public static string Text_CloseProject {
            get {
                return ResourceManager.GetString("Text_CloseProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile.
        /// </summary>
        public static string Text_Compile {
            get {
                return ResourceManager.GetString("Text_Compile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiler files copied..
        /// </summary>
        public static string Text_CompilerFilesCopied {
            get {
                return ResourceManager.GetString("Text_CompilerFilesCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpacking compiler files completed. Proceed with copying files....
        /// </summary>
        public static string Text_CompilerFilesCopying {
            get {
                return ResourceManager.GetString("Text_CompilerFilesCopying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading compiler files....
        /// </summary>
        public static string Text_CompilerFilesDownloading {
            get {
                return ResourceManager.GetString("Text_CompilerFilesDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiler files couldn&apos;t be downloaded. Proceed with program startup....
        /// </summary>
        public static string Text_CompilerFilesError {
            get {
                return ResourceManager.GetString("Text_CompilerFilesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download completed. Unpacking compiler files....
        /// </summary>
        public static string Text_CompilerFilesUnpacking {
            get {
                return ResourceManager.GetString("Text_CompilerFilesUnpacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiler Options.
        /// </summary>
        public static string Text_CompilerOptions {
            get {
                return ResourceManager.GetString("Text_CompilerOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Text_Copy {
            get {
                return ResourceManager.GetString("Text_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Text_Create {
            get {
                return ResourceManager.GetString("Text_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Document.
        /// </summary>
        public static string Text_CurrentDocument {
            get {
                return ResourceManager.GetString("Text_CurrentDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string Text_Cut {
            get {
                return ResourceManager.GetString("Text_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Text_Delete {
            get {
                return ResourceManager.GetString("Text_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Text_Edit {
            get {
                return ResourceManager.GetString("Text_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Text_Exit {
            get {
                return ResourceManager.GetString("Text_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string Text_File {
            get {
                return ResourceManager.GetString("Text_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filterscript.
        /// </summary>
        public static string Text_Filterscript {
            get {
                return ResourceManager.GetString("Text_Filterscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string Text_Find {
            get {
                return ResourceManager.GetString("Text_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Next.
        /// </summary>
        public static string Text_FindNext {
            get {
                return ResourceManager.GetString("Text_FindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Prev..
        /// </summary>
        public static string Text_FindPrevious {
            get {
                return ResourceManager.GetString("Text_FindPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to find:.
        /// </summary>
        public static string Text_FindWhat {
            get {
                return ResourceManager.GetString("Text_FindWhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string Text_Folder {
            get {
                return ResourceManager.GetString("Text_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamemode.
        /// </summary>
        public static string Text_Gamemode {
            get {
                return ResourceManager.GetString("Text_Gamemode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To.
        /// </summary>
        public static string Text_GoTo {
            get {
                return ResourceManager.GetString("Text_GoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include.
        /// </summary>
        public static string Text_Include {
            get {
                return ResourceManager.GetString("Text_Include", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line number (1- {0}):.
        /// </summary>
        public static string Text_LineNumber {
            get {
                return ResourceManager.GetString("Text_LineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading plugins....
        /// </summary>
        public static string Text_LoadingPlugins {
            get {
                return ResourceManager.GetString("Text_LoadingPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look in:.
        /// </summary>
        public static string Text_LookIn {
            get {
                return ResourceManager.GetString("Text_LookIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Text_Name {
            get {
                return ResourceManager.GetString("Text_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Text_New {
            get {
                return ResourceManager.GetString("Text_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Text_OK {
            get {
                return ResourceManager.GetString("Text_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Text_Open {
            get {
                return ResourceManager.GetString("Text_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Text_Options {
            get {
                return ResourceManager.GetString("Text_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Text_Paste {
            get {
                return ResourceManager.GetString("Text_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string Text_Path {
            get {
                return ResourceManager.GetString("Text_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin &quot;{0}&quot; loded..
        /// </summary>
        public static string Text_PluginLoaded {
            get {
                return ResourceManager.GetString("Text_PluginLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Text_Project {
            get {
                return ResourceManager.GetString("Text_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string Text_Redo {
            get {
                return ResourceManager.GetString("Text_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Text_Rename {
            get {
                return ResourceManager.GetString("Text_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string Text_Replace {
            get {
                return ResourceManager.GetString("Text_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace All.
        /// </summary>
        public static string Text_ReplaceAll {
            get {
                return ResourceManager.GetString("Text_ReplaceAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to replace:.
        /// </summary>
        public static string Text_ReplaceWith {
            get {
                return ResourceManager.GetString("Text_ReplaceWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save {0}.
        /// </summary>
        public static string Text_Save {
            get {
                return ResourceManager.GetString("Text_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save All.
        /// </summary>
        public static string Text_SaveAll {
            get {
                return ResourceManager.GetString("Text_SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save {0} As....
        /// </summary>
        public static string Text_SaveAs {
            get {
                return ResourceManager.GetString("Text_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Item.
        /// </summary>
        public static string Text_SelectedItem {
            get {
                return ResourceManager.GetString("Text_SelectedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server files copied..
        /// </summary>
        public static string Text_ServerFilesCopied {
            get {
                return ResourceManager.GetString("Text_ServerFilesCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpacking server files completed. Proceed with copying files....
        /// </summary>
        public static string Text_ServerFilesCopying {
            get {
                return ResourceManager.GetString("Text_ServerFilesCopying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading server files....
        /// </summary>
        public static string Text_ServerFilesDownloading {
            get {
                return ResourceManager.GetString("Text_ServerFilesDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server files couldn&apos;t be downloaded. Proceed with compiler files....
        /// </summary>
        public static string Text_ServerFilesError {
            get {
                return ResourceManager.GetString("Text_ServerFilesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download completed. Unpacking server files....
        /// </summary>
        public static string Text_ServerFilesUnpacking {
            get {
                return ResourceManager.GetString("Text_ServerFilesUnpacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in Explorer.
        /// </summary>
        public static string Text_ShowInExplorer {
            get {
                return ResourceManager.GetString("Text_ShowInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting up....
        /// </summary>
        public static string Text_Starting {
            get {
                return ResourceManager.GetString("Text_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Text_Type {
            get {
                return ResourceManager.GetString("Text_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Text_Undo {
            get {
                return ResourceManager.GetString("Text_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception has occurred in application.
        ///If you click continue the application will ignore this issue and attempt to continue. 
        ///If you click quit, the application will close immediately..
        /// </summary>
        public static string Text_UnhandledExceptionOccurred {
            get {
                return ResourceManager.GetString("Text_UnhandledExceptionOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for old version....
        /// </summary>
        public static string Text_VersionChecking {
            get {
                return ResourceManager.GetString("Text_VersionChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtain settings from the old version....
        /// </summary>
        public static string Text_VersionSettings {
            get {
                return ResourceManager.GetString("Text_VersionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whole Word.
        /// </summary>
        public static string Text_WholeWord {
            get {
                return ResourceManager.GetString("Text_WholeWord", resourceCulture);
            }
        }
    }
}
