using DigitalRune.Windows.TextEditor;
using DigitalRune.Windows.TextEditor.Completion;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Windows.Forms;

namespace PawnPlus.Core.Document
{
    public class CodeCompletionDataProvider : AbstractCompletionDataProvider, IDisposable // With 'IDisposable' it will avoid warning generated by Code Analysis.
    {
        private readonly ImageList imageList;

        public override ImageList ImageList
        {
            get { return imageList; }
        }

        public CodeCompletionDataProvider()
        {
            imageList = new ImageList();
            imageList.Images.Add(Properties.Resources.text_16xLG);
            imageList.Images.Add(Properties.Resources.field_16xLG);
            imageList.Images.Add(Properties.Resources.method_16xLG);

        }


        public override ICompletionData[] GenerateCompletionData(string fileName, TextArea textArea, char charTyped)
        {
            List<ICompletionData> completionData = new List<ICompletionData>();

            foreach (KeyValuePair<string, MethodInformations> CodeCompletion in MethodsProvider.Methods)
            {
                completionData.Add(new DefaultCompletionData(CodeCompletion.Key, CodeCompletion.Value.Description, 2));
            }

            // Add some snippets (text templates).
            List<Snippet> snippets = new List<Snippet>
              {
                new Snippet("for", "for (|;;)\n{\n}", "Code snippet for 'for' loop"),
                new Snippet("if", "if (|)\n{\n}", "Code snippet for if statement"),
                new Snippet("ifel", "if (|)\n{\n}\nelse\n{\n}", "Code snippet for if-else statement"),
                new Snippet("while", "while (|)\n{\n}", "Code snippet for while loop"),
                new Snippet("switch", "switch (|)\n{\n}", "Code snippet for switch statement"),
              };

            // Add the snippets to the completion data
            foreach (Snippet snippet in snippets)
                completionData.Add(new SnippetCompletionData(snippet, 0));

            return completionData.ToArray();
        }

        #region Dispose Methods
        
        protected virtual void Dispose(bool Disposing)
        {
            if (Disposing == true)
            {
                this.imageList.Dispose();
            }

        }

        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }
        
        #endregion
    }
}
