using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Windows.Forms;
using System.Xml;

namespace PawnPlus
{
    public partial class CreateProject : Form
    {
        private Stream resourceStream = null;

        public CreateProject()
        {
            InitializeComponent();
        }

        private void BrowseFolder_Click(object sender, EventArgs e)
        {
            if (FolderBrowserDialog.ShowDialog(this) == DialogResult.OK)
                ProjectPathText.Text = FolderBrowserDialog.SelectedPath;
        }

        private void OkButton_Click(object sender, EventArgs e)
        {
            if (ProjectNameText.Text.Length == 0)
            {
                MessageBox.Show("You haven't entered the project name!");

                return;
            }
            else if (ProjectPathText.Text.Length == 0)
            {
                MessageBox.Show("You haven't entered the project path!");

                return;
            }
            else if (Directory.EnumerateFileSystemEntries(FolderBrowserDialog.SelectedPath).Any())
            {
                MessageBox.Show("Project directory must be empty!");

                return;
            }

            // Create project files.

            XmlDocument Project = new XmlDocument();
            XmlElement Element;
            XmlText Text;

            XmlDeclaration xmlDeclaration = Project.CreateXmlDeclaration("1.0", "UTF-8", null);
            XmlElement Root = Project.DocumentElement;
            Project.InsertBefore(xmlDeclaration, Root);

            XmlElement ProjectTag = Project.CreateElement(string.Empty, "Project", string.Empty);
            Project.AppendChild(ProjectTag);

            Element = Project.CreateElement(string.Empty, "Name", string.Empty);
            Text = Project.CreateTextNode(ProjectNameText.Text);
            Element.AppendChild(Text);
            ProjectTag.AppendChild(Element);

            Project.Save(Path.Combine(FolderBrowserDialog.SelectedPath, ProjectNameText.Text + ".pawnplusproject"));

            Directory.CreateDirectory(Path.Combine(FolderBrowserDialog.SelectedPath, "filterscripts"));
            Directory.CreateDirectory(Path.Combine(FolderBrowserDialog.SelectedPath, "gamemodes"));
            Directory.CreateDirectory(Path.Combine(FolderBrowserDialog.SelectedPath, "npcmodes"));
            Directory.CreateDirectory(Path.Combine(FolderBrowserDialog.SelectedPath, "plugins"));
            Directory.CreateDirectory(Path.Combine(FolderBrowserDialog.SelectedPath, "scriptfiles"));

            // With this 'try' it will avoid warning generated by Code Analysis.
            try
            {
                this.resourceStream = Assembly.GetExecutingAssembly().GetManifestResourceStream("PawnPlus.Resources.DefaultFilterscript.pwn");

                using (StreamReader reader = new StreamReader(resourceStream))
                {
                    this.resourceStream = null;
                    File.WriteAllText(Path.Combine(Path.Combine(FolderBrowserDialog.SelectedPath, "filterscripts"), ProjectNameText.Text + "_filterscript.pwn"), reader.ReadToEnd());
                }
            }
            finally
            {
                if (this.resourceStream != null)
                    this.resourceStream.Dispose();
            }

            // With this 'try' it will avoid warning generated by Code Analysis.
            try
            {
                this.resourceStream = Assembly.GetExecutingAssembly().GetManifestResourceStream("PawnPlus.Resources.DefaultGameMode.pwn");

                using (StreamReader reader = new StreamReader(resourceStream))
                {
                    this.resourceStream = null;
                    File.WriteAllText(Path.Combine(Path.Combine(FolderBrowserDialog.SelectedPath, "gamemodes"), ProjectNameText.Text + ".pwn"), reader.ReadToEnd());
                }
            }
            finally
            {
                if (this.resourceStream != null)
                    this.resourceStream.Dispose();
            }
            Program.main.LoadProject(Path.Combine(FolderBrowserDialog.SelectedPath, ProjectNameText.Text + ".pawnplusproject"));

            this.Close();
        }

        private void CancelButton_Click(object sender, EventArgs e)
        {
            this.Close();
        }
    }
}
